# Generated by Django 2.0.13 on 2020-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_rating', models.FloatField()),
                ('rating_users', models.CharField(max_length=200)),
            ],
        ),
    ]
