# Generated by Django 2.0.13 on 2020-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslist',
            name='movie_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
